### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by Trenly**
Lint Files

### CODE REVIEW

**Comment by stephengillie** [comment]
Are single quotes preferred now? In the past there was no preference.

**Comment by Trenly** [comment]
> Are single quotes preferred now? In the past there was no preference.



> Are single quotes preferred now? In the past there was no preference.

It's just the way I have the PowerShell extension set up. Single quoted strings are often seen as "safer" since they are literal and don’t substitute in for variables, which can also occasionally provide some slight runtime optimizations in memory allocation

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.4

**Comment by stephengillie** [comment]
> It's just the way I have the PowerShell extension set up. Single quoted strings are often seen as "safer" since they are literal and don’t substitute in for variables, which can also occasionally provide some slight runtime optimizations in memory allocation
> 
> https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.4

This behavior is unique to PowerShell, afaik. Most languages treat them interchangeably, in my experience. It's hard to find guidance at all on this for PowerShell, and almost all guidance says there is no preference. One reddit post provided this same link as proof of no preference. Also: 

- Single quoted strings need to escape apostrophes. 
- English natural language conventions dictate double quotes, except for nested quotes.

**Comment by Trenly** [comment]
> This behavior is unique to PowerShell, afaik. Most languages treat them interchangeably, in my experience.

I don't think so; It's essentially the difference between a string literal and a string object. One can be referenced in static memory, the other generates a pointer. Basically it's .NET string interning.

> It's hard to find guidance at all on this for PowerShell, and almost all guidance says there is no preference. One reddit post provided this same link as proof of no preference. Also:
> 
> * Single quoted strings need to escape apostrophes.
> * English natural language conventions dictate double quotes, except for nested quotes.

It's a bit of an older article, but it talks about how the string interpreter works for singly vs doubly quoted strings - https://jon.netdork.net/2015/09/08/powershell-and-single-vs-double-quotes/

----

In a practical sense, it doesn't really make much of a difference, since it isn't like there's thousands of strings or thousands of calls accessing the strings, and I'm sure that improvements have been made since the article to bring the processing times closer together.

**Pull request closed without merging**
